# Generated by Django 4.2.9 on 2024-02-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0003_alter_funcionario_user"),
        ("documentos", "0002_documento_pertence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="pertence",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="funcionarios.funcionario",
            ),
            preserve_default=False,
        ),
    ]
