# Generated by Django 5.0.1 on 2024-03-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documento_pertence'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento',
            field=models.FileField(default=1, upload_to='documentos'),
            preserve_default=False,
        ),
    ]
