# Generated by Django 5.0.1 on 2024-03-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='documento',
            new_name='arquivo',
        ),
    ]
